# Generated by Django 3.1.1 on 2020-09-04 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(verbose_name='Rows')),
                ('columns', models.PositiveIntegerField(verbose_name='Columns')),
                ('mines', models.PositiveIntegerField(verbose_name='Mines')),
            ],
            options={
                'verbose_name': 'Board template',
                'verbose_name_plural': 'Board templates',
                'ordering': ['rows', 'columns', 'mines'],
                'unique_together': {('rows', 'columns', 'mines')},
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(verbose_name='Rows')),
                ('columns', models.PositiveIntegerField(verbose_name='Columns')),
                ('mines', models.PositiveIntegerField(verbose_name='Mines')),
                ('board_json', models.JSONField(editable=False, verbose_name='Board JSON')),
                ('finished', models.BooleanField(blank=True, default=False, editable=False, verbose_name='Finished')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='minesweeper_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'unique_together': {('rows', 'columns', 'mines')},
            },
        ),
    ]
